// <auto-generated />
using System;
using CaseyHub.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaseyHub.API.Migrations
{
    [DbContext(typeof(CaseyHubDbContext))]
    [Migration("20260430042539_AddPermitChecker")]
    partial class AddPermitChecker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaseyHub.Core.Entities.BuildingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BuildingTypes");
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.Permit", b =>
                {
                    b.Property<string>("ApplicationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("AdvertiseCommencedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AdvertiseCompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApplicationCategory")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Decision")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionStage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LodgedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceArea")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ApplicationNumber");

                    b.ToTable("Permits");
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.PermitAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("AssessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BuildingTypeSlug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("NormalisedAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OutcomeReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OverlayCodes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TriggeredClauseNumbers")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ZoneCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AssessedAtUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("BuildingTypeSlug", "Outcome");

                    b.ToTable("PermitAssessments");
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.PermitRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OutcomeReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PlanningClauseId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("ShortCircuitOnMatch")
                        .HasColumnType("boolean");

                    b.Property<string>("TriggerContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BuildingTypeId");

                    b.HasIndex("PlanningClauseId");

                    b.ToTable("PermitRules");
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.PlanningClause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClauseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OfficialUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ClauseNumber")
                        .IsUnique();

                    b.ToTable("PlanningClauses");
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.RuleQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HelpText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("PermitRuleId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ValidationJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("PermitRuleId");

                    b.ToTable("RuleQuestions");
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.ZoneOverrideRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OutcomeReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PlanningClauseId")
                        .HasColumnType("integer");

                    b.Property<bool>("PrefixMatch")
                        .HasColumnType("boolean");

                    b.Property<string>("ZoneOrOverlayCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingTypeId");

                    b.HasIndex("PlanningClauseId");

                    b.ToTable("ZoneOverrideRules");
                });

            modelBuilder.Entity("UserSavedPermits", b =>
                {
                    b.Property<string>("ApplicationNumber")
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ApplicationNumber", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSavedPermits");
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.Permit", b =>
                {
                    b.OwnsOne("CaseyHub.Core.Entities.Location", "Location", b1 =>
                        {
                            b1.Property<string>("PermitApplicationNumber")
                                .HasColumnType("character varying(100)");

                            b1.Property<Point>("Coordinates")
                                .HasColumnType("geography (Point, 4326)")
                                .HasColumnName("Coordinates");

                            b1.Property<string>("HouseNumber")
                                .HasColumnType("text")
                                .HasColumnName("HouseNumber");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Longitude");

                            b1.Property<string>("Municipality")
                                .HasColumnType("text")
                                .HasColumnName("Municipality");

                            b1.Property<string>("Postcode")
                                .HasColumnType("text")
                                .HasColumnName("Postcode");

                            b1.Property<string>("RawAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("RawAddress");

                            b1.Property<string>("State")
                                .HasColumnType("text")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .HasColumnType("text")
                                .HasColumnName("Street");

                            b1.Property<string>("Suburb")
                                .HasColumnType("text")
                                .HasColumnName("Suburb");

                            b1.HasKey("PermitApplicationNumber");

                            b1.ToTable("Permits");

                            b1.WithOwner()
                                .HasForeignKey("PermitApplicationNumber");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.PermitRule", b =>
                {
                    b.HasOne("CaseyHub.Core.Entities.BuildingType", "BuildingType")
                        .WithMany("PermitRules")
                        .HasForeignKey("BuildingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaseyHub.Core.Entities.PlanningClause", "PlanningClause")
                        .WithMany()
                        .HasForeignKey("PlanningClauseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuildingType");

                    b.Navigation("PlanningClause");
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.RuleQuestion", b =>
                {
                    b.HasOne("CaseyHub.Core.Entities.PermitRule", "PermitRule")
                        .WithMany("Questions")
                        .HasForeignKey("PermitRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermitRule");
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.ZoneOverrideRule", b =>
                {
                    b.HasOne("CaseyHub.Core.Entities.BuildingType", "BuildingType")
                        .WithMany("ZoneOverrideRules")
                        .HasForeignKey("BuildingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaseyHub.Core.Entities.PlanningClause", "PlanningClause")
                        .WithMany()
                        .HasForeignKey("PlanningClauseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuildingType");

                    b.Navigation("PlanningClause");
                });

            modelBuilder.Entity("UserSavedPermits", b =>
                {
                    b.HasOne("CaseyHub.Core.Entities.Permit", null)
                        .WithMany()
                        .HasForeignKey("ApplicationNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseyHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.BuildingType", b =>
                {
                    b.Navigation("PermitRules");

                    b.Navigation("ZoneOverrideRules");
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.PermitRule", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
