// <auto-generated />
using System;
using CaseyHub.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaseyHub.API.Migrations
{
    [DbContext(typeof(CaseyHubDbContext))]
    [Migration("20260423035126_UserPermits")]
    partial class UserPermits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaseyHub.Core.Entities.Permit", b =>
                {
                    b.Property<string>("ApplicationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("AdvertiseCommencedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AdvertiseCompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApplicationCategory")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Decision")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionStage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LodgedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceArea")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ApplicationNumber");

                    b.ToTable("Permits");
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserSavedPermits", b =>
                {
                    b.Property<string>("ApplicationNumber")
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ApplicationNumber", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSavedPermits");
                });

            modelBuilder.Entity("CaseyHub.Core.Entities.Permit", b =>
                {
                    b.OwnsOne("CaseyHub.Core.Entities.Location", "Location", b1 =>
                        {
                            b1.Property<string>("PermitApplicationNumber")
                                .HasColumnType("character varying(100)");

                            b1.Property<Point>("Coordinates")
                                .HasColumnType("geography (Point, 4326)")
                                .HasColumnName("Coordinates");

                            b1.Property<string>("HouseNumber")
                                .HasColumnType("text")
                                .HasColumnName("HouseNumber");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Longitude");

                            b1.Property<string>("Municipality")
                                .HasColumnType("text")
                                .HasColumnName("Municipality");

                            b1.Property<string>("Postcode")
                                .HasColumnType("text")
                                .HasColumnName("Postcode");

                            b1.Property<string>("RawAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("RawAddress");

                            b1.Property<string>("State")
                                .HasColumnType("text")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .HasColumnType("text")
                                .HasColumnName("Street");

                            b1.Property<string>("Suburb")
                                .HasColumnType("text")
                                .HasColumnName("Suburb");

                            b1.HasKey("PermitApplicationNumber");

                            b1.ToTable("Permits");

                            b1.WithOwner()
                                .HasForeignKey("PermitApplicationNumber");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("UserSavedPermits", b =>
                {
                    b.HasOne("CaseyHub.Core.Entities.Permit", null)
                        .WithMany()
                        .HasForeignKey("ApplicationNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseyHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
